import 'package:flutter/material.dart';


class TermsAndCondation extends StatefulWidget {
  @override
  _TermsAndCondationState createState() => _TermsAndCondationState();
}

class _TermsAndCondationState extends State<TermsAndCondation> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor:Colors.white,
      appBar: AppBar(
        backgroundColor: Color.fromRGBO(247, 190, 197, 1),
        centerTitle: true,
        title: new Text(' Terms And Condation'),
      ),

      body: new ListView(
        scrollDirection: Axis.vertical,
        children: <Widget>[
          Container(
            padding: EdgeInsets.only(top: 5.0,left: 10.0),
            child: Image.asset('images/logoo.png',
              height: 80.0,
            ),
          ),
          SizedBox(height: 20.0,),
          Container(
            padding: EdgeInsets.only(left: 15.0,),
            child: new Text('LUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS SILK FOUNDATIONLUMINOUS SILK FOUNDATIONLUMINOUSLUMINOUS  '),
          )
        ],
      ),
    );
  }
}
