name: applogo
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.11.3+17


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/logo.png
    - images/background1.png
    - images/advertis.png
    - images/advertis1.png
    - images/advertis2.png
    - images/like.png
    - images/love.png
    - images/notification1.png
    - images/redcard.png
    - images/share.png
    - images/black.png
    - images/black1.png
    - images/black3.png
    - images/red.png
    - images/red1.png
    - images/white.png
    - images/white1.png
    - images/call.png
    - images/fax1.png
    - images/link.png
    - images/maps.png
    - images/message.png
    - images/paper.png
    - images/share.png
    - images/makeup.jpg
    - images/share1.png
    - images/dollar.png
    - images/background2.png
    - images/makeup1.jpg
    - images/background.png
    - images/help.png
    - images/flag1.png
    - images/earth.png
    - images/information.png
    - images/sign.png
    - images/smartphon.png
    - images/makeup.png
    - images/perfume.png
    - images/group.png
    - images/tourguide.png
    - images/tourguide1.png
    - images/tourguide2.png
    - images/tourguide3.png
    - images/logoo.png
    - images/notification1.png
    - images/notifiaction2.png
    - images/notification3.png
    - images/notification4.png
    - images/notification5.png
    - images/success1.png


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
